### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by cwurld** [hostmaster/ansible-digitalocean-bootstrap#3]
I am getting the error:

failed: [localhost] => {"failed": true}
msg: Access Denied

The only thing I can find that I am doing different from you is I add:

ansible_python_interpreter: "/home/me/.virtualenvs/roi_digital_ocean/bin/python"

to vars.yml. 

Any ideas how to resolve this? Thanks.

**Comment by TotalLag** [comment]
how are you running the playbook? i think even if it's localhost, ansible will utilize ssh. you have to also pass "-c local" so it runs locally.

``` bash
$ ansible-playbook -c local playbook.yml
```

**Comment by cwurld** [comment]
Thanks.
